version: 2
project_name: bunster
builds:
  - id: bunster
    main: ./
    binary: bunster_{{ .Os }}-{{ .Arch }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
checksum:
  name_template: "checksums.txt"
